# Generated by Django 5.1.6 on 2025-04-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_remove_recipe_is_favorited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_subscribed',
        ),
    ]
