# Generated by Django 5.1.6 on 2025-04-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_favorite_options_alter_shoppingcart_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foodgram/images/recipes', verbose_name='Изображение рецепта'),
        ),
    ]
